### ISSUE TITLE
permission_required

### ISSUE THREAD

**Issue by juandgc** [un33k/django-menuware#1]
Greetings, this app has a option for permission_required?

**Comment by un33k** [comment]
It supports method registration where a user permission can be checked. `request` is passed into the function prior to rendering.  Look for the `is_user_is_paid_customer` in the [README](https://github.com/un33k/django-menuware/blob/master/README.md#how-to-use-simple) file.

**Comment by juandgc** [comment]
can i pass another parameter? because i need to know which permission need to be checked

**Comment by un33k** [comment]
No. you can write a very simple middleware to add the extra fields to the `request` dict.

**Comment by juandgc** [comment]
Thank you very much.
